name: Cypress Tests
on: [push] # Triggers on every code push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          # Optional: starts your app before running tests
          start: npm start 
          # Optional: waits for the server to be ready
          wait-on: 'http://localhost:3000' 
          record: true
        # projectId can be in cypress.config.js, the record key is stored as a GitHub secre  
          record-key: ${{ secrets.CYPRESS_RECORD_KEY }}   
          